title: Ahmed's Bold Creations # ABC acronym
url: https://ahmedalh7876.github.io
author: Ahmed Al-Hayali
email: awalhialy@yahoo.com
description: > # this means to ignore newlines until "show_exerpts:"
Welcome to Ahmed's Bold Creations (ABC, I'm not too creative). I'm Ahmed, a 2nd-year Software Engineering
student @ McMaster University in Hamilton. This site will be host to the scattered collection of projects
and/or learning materials that I create. Enjoy the gallery. 
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

#  disqus:
#    shortname: bitbrain-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://github.com/bitbrain
      icon: github-square
      color: yellow

# Build settings
theme: jekyll-dash

plugins:
  - liquid-md5
  - jekyll/tagging
